test_dataset:
  dataset:
    name: mc-image-folders
    args:
      root_path_1: /ssd/dataset/pyw/dataset/IVDM3Seg/test/wat
      root_path_2: /ssd/dataset/pyw/dataset/IVDM3Seg/test/fat
      # root_path_1: /ssd/dataset/pyw/dataset/IVDM3Seg/test/wat_exp
      # root_path_2: /ssd/dataset/pyw/dataset/IVDM3Seg/test/fat_exp
      # root_path_1: /ssd/dataset/pyw/dataset/IVDM3Seg/test/wat_fig1
      # root_path_2: /ssd/dataset/pyw/dataset/IVDM3Seg/test/fat_fig1
      first_k: 160
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale_max: 12
  batch_size: 8




#eval_type: None
#eval_bsize: None

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  ref: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}




